nodeLinker: node-modules

npmRegistries:
  //registry.tiptap.dev:
    npmAlwaysAuth: true
    npmAuthToken: DoMXUpj8CLfv33OISxQVT/JFfmvuH4jZXj6Esm8oaC0aH8asBT1pl9lksE8n4KEI

npmScopes:
  tiptap-pro:
    npmRegistryServer: "https://registry.tiptap.dev/"
